### ISSUE TITLE
Složiti rotirajuće portove za streaming upite

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/B.A.R.I.C.A.#3]
U backendapi.py funkcija get_stream_port() trenutno počinje od porta 2000 i za svaki zahtjev za portom povećava zadnji port za jedan i vraća taj port. Trebalo bi složiti rotaciju portova, tj. da primjerice nakon porta 4999 se opet vrati na 2000. Kako bi to funkcioniralo, potrebno je redovito zatvarati portove koji se više ne koriste, tj. kreirati dretvu koja će prolaziti kroz listu portova i brisati one koji se više ne koriste. Također, bilo bi korisno da se prije vraćanja porta u funkciju doda provjera je li port zauzet ili nije, kako se ne bi vraćao zauzeti port. Na kraju, potrebno je implementirati pogrešku tipa NoAvailablePorts (vidi npr. ModuleException u istoj datoteci) koja će se vraćati u slučaju da su svi portovi zauzeti.

**Comment by elvispopovic** [comment]
Ako bih radio na ovome, kako mogu commitati rezultat? Samo sam forkao projekt, ali nisam član projekta.

**Comment by mschatten** [comment]
Samo pošaljite pull request, pa ćemo napraviti merge u glavni projekt.

**Comment by elvispopovic** [comment]
Riješio sam. Molim upute za upload na git.

**Comment by mschatten** [comment]
Ako ste napravili fork, treba negdje biti opcija za pull request. https://help.github.com/en/articles/creating-a-pull-request

**Comment by mschatten** [comment]
Odnosno ovdje ako ste napravili fork https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
